### ISSUE TITLE
Enemies not instantly dying when hp reaches 0

### ISSUE THREAD

**Issue by Testing0123** [SometimesRain/crazyclient#11] opened 2017-04-21 20:36 UTC
For example just say I use a Doombow and hit a 1000hp god with 1050 damage. Normally, the god would disappear instantly and the damage number wouldn't even show, which is good. But in v9, it gets to 0 hp, doesn't let me shoot it anymore, then after half a second it disappears. 

On its own this is not a problem, but if it gets healed in that half second, it stays alive but is treated as dead by the client and I can't damage it anymore (shots go through it), but it can damage me. This only happens in v9, so something must have changed,

**Comment by SirAnuse** [comment] 2017-04-22 00:06
I believe this is a fix to the invisible enemies bug which was happening previously. Well, it's at least an attempted fix. Hopefully it'll work.

Is this really a problem, though? Sure, it might be annoying, but hopefully it's a fix to the invisible enemies bug. Also, I believe that when you one shot a ghost god, it's still there for half a second on the server's side due to latency. I think that's probably what's happening, the ghost god is being displayed as it is on the server.

**Comment by SometimesRain** [comment] 2017-04-25 13:53
This is caused by the way I fixed invisible enemies. It checks if you receive an update for an invisible enemy and turns it visible again. Because the mobs don't die on the server immediately when you kill them on you client, you receive some updates even after the mob has died.

Adding a delay to the "turn back visible" function would solve this but that requires me to track the time when an update for each individual mob was received.

**Closed as completed** 2017-04-26 11:48 UTC
Labels: bug
